name: Canary Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    paths:
      - Otakulore/**
  workflow_dispatch:
jobs:
  main:
    uses: dentolos19/ActionsPlayground/.github/workflows/REUSABLE-dotnet-maui.yml@main
    with:
      TARGET_BRANCH: ${{ github.event.repository.default_branch }}
      PROJECT_FILE: Otakulore/Otakulore.csproj
      RELEASE_TAG: Canary
      WINDOWS_TARGET_FRAMEWORK: net7.0-windows10.0.19041.0
      ANDROID_TARGET_FRAMEWORK: net7.0-android
    secrets:
      SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}